services:
  qwen3:
    build: 
      context: ./qwen3_tts
      dockerfile: Dockerfile
    container_name: comfyui-standalone
    ipc: host
    ports:
      - "8188:8188"
    volumes:
      - ./qwen3_tts/input:/app/input
      - ./qwen3_tts/output:/app/output
      - ./qwen3_tts/cache:/root/.cache/huggingface 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]