from .character_edit import (
    NODE_CLASS_MAPPINGS as EDIT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EDIT_NODE_DISPLAY_NAME_MAPPINGS,
)

from .prepare_characters import (
    NODE_CLASS_MAPPINGS as PREPARE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PREPARE_NODE_DISPLAY_NAME_MAPPINGS,
)

from .prepare_character_references import (
    NODE_CLASS_MAPPINGS as PREPARE_REFERENCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PREPARE_REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
)

from .scene_prompt import (
    NODE_CLASS_MAPPINGS as SCENE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCENE_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {
    **EDIT_NODE_CLASS_MAPPINGS,
    **PREPARE_NODE_CLASS_MAPPINGS,
    **PREPARE_REFERENCE_NODE_CLASS_MAPPINGS,
    **SCENE_NODE_CLASS_MAPPINGS,
}


NODE_DISPLAY_NAME_MAPPINGS = {
    **EDIT_NODE_DISPLAY_NAME_MAPPINGS,
    **PREPARE_NODE_DISPLAY_NAME_MAPPINGS,
    **PREPARE_REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
    **SCENE_NODE_DISPLAY_NAME_MAPPINGS,
}


WEB_DIRECTORY = "./web"


__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]