from nodes import CLIPTextEncode

from .character_utils import apply_character_reference


# ============================================================================
# Custom Types
# ============================================================================

CharacterReferences = "CHARACTER_REFERENCES"


# ============================================================================
# D&D Scene Prompt
# ============================================================================

class DNDScenePrompt:
    """
    Build the final positive scene prompt.

    Inputs:

        CLIP
            Flux text encoder.

        CHARACTER_CONTEXT
            Textual descriptions, Preserve instructions, and Avoid
            instructions generated by DNDPrepareCharacters.

        CHARACTER_REFERENCES
            Actual reference images loaded from the character library.

        VAE
            VAE used to encode the character reference images into
            the conditioning.

        SCENE
            Actual scene/action/environment instructions.

    The node:

        1. Builds the textual prompt.
        2. Encodes it using ComfyUI's native CLIPTextEncode.
        3. Applies every character reference image to the conditioning.
        4. Returns standard CONDITIONING.

    This means the reference images are actually part of the Flux Kontext
    conditioning rather than merely being mentioned by filename in text.
    """

    @classmethod
    def INPUT_TYPES(cls):

        return {
            "required": {

                # ============================================================
                # CLIP
                # ============================================================

                "clip": (
                    "CLIP",
                ),

                # ============================================================
                # Character textual context
                # ============================================================

                "character_context": (
                    "STRING",
                    {
                        "default": "",
                        "multiline": True,
                        "dynamicPrompts": False,
                    },
                ),

                # ============================================================
                # Character reference images
                # ============================================================

                "character_references": (
                    CharacterReferences,
                ),

                # ============================================================
                # VAE
                # ============================================================

                "vae": (
                    "VAE",
                ),

                # ============================================================
                # Scene
                # ============================================================

                "scene": (
                    "STRING",
                    {
                        "default": "",
                        "multiline": True,
                        "dynamicPrompts": False,
                    },
                ),
            }
        }


    RETURN_TYPES = (
        "CONDITIONING",
    )

    RETURN_NAMES = (
        "CONDITIONING",
    )

    FUNCTION = "build_scene_prompt"

    CATEGORY = "D&D Images/Prompts"


    def build_scene_prompt(
        self,
        clip,
        character_context,
        character_references,
        vae,
        scene,
    ):

        character_context = (
            character_context or ""
        ).strip()

        scene = (
            scene or ""
        ).strip()


        # ====================================================================
        # Build textual prompt
        # ====================================================================

        sections = []


        # --------------------------------------------------------------------
        # Character Context
        # --------------------------------------------------------------------

        if character_context:

            sections.append(
                "CHARACTER CONTEXT:\n"
                + character_context
            )


        # --------------------------------------------------------------------
        # Scene
        # --------------------------------------------------------------------

        if scene:

            sections.append(
                "SCENE:\n"
                + scene
            )


        # --------------------------------------------------------------------
        # Final prompt
        # --------------------------------------------------------------------

        prompt = "\n\n".join(
            sections
        )


        # ====================================================================
        # Encode text using ComfyUI's native CLIPTextEncode
        # ====================================================================

        encoded = CLIPTextEncode().encode(
            clip=clip,
            text=prompt,
        )

        conditioning = encoded[0]


        # ====================================================================
        # Apply character reference images
        # ====================================================================

        if character_references:

            for reference in character_references:

                if not isinstance(
                    reference,
                    dict,
                ):
                    continue

                image = reference.get(
                    "image"
                )

                if image is None:
                    continue

                conditioning = (
                    apply_character_reference(
                        image=image,
                        conditioning=conditioning,
                        vae=vae,
                    )
                )


        # ====================================================================
        # Return final conditioning
        # ====================================================================

        return (
            conditioning,
        )


# ============================================================================
# Node Registration
# ============================================================================

NODE_CLASS_MAPPINGS = {
    "DNDScenePrompt": DNDScenePrompt,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "DNDScenePrompt": "D&D Scene Prompt",
}